/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import javax.swing.JOptionPane;

/**
 *
 * @author ferdinand ATTIVI
 */
public class Calculatrice extends javax.swing.JFrame {

    /**
     * Creates new form Calculatrice
     */
    public Calculatrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre1Label = new javax.swing.JLabel();
        Nombre1Field = new javax.swing.JTextField();
        OppLabel = new javax.swing.JLabel();
        Nombre2Label = new javax.swing.JLabel();
        Nombre2Field = new javax.swing.JTextField();
        CalculerBtn = new javax.swing.JButton();
        resultatPanel = new javax.swing.JPanel();
        ResultatField = new javax.swing.JTextField();
        OppField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculatrice", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        Nombre1Label.setText("Nombre1 ");

        Nombre1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1FieldActionPerformed(evt);
            }
        });

        OppLabel.setText("Operation");

        Nombre2Label.setText("Nombre 2");

        Nombre2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre2FieldActionPerformed(evt);
            }
        });

        CalculerBtn.setText("Calculer");
        CalculerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculerBtnActionPerformed(evt);
            }
        });

        resultatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultat", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        ResultatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultatFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultatPanelLayout = new javax.swing.GroupLayout(resultatPanel);
        resultatPanel.setLayout(resultatPanelLayout);
        resultatPanelLayout.setHorizontalGroup(
            resultatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultatField)
                .addContainerGap())
        );
        resultatPanelLayout.setVerticalGroup(
            resultatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ResultatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        OppField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "/", "*" }));
        OppField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OppFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CalculerBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre1Label)
                                    .addComponent(OppLabel)
                                    .addComponent(Nombre2Label))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nombre1Field)
                                    .addComponent(Nombre2Field)
                                    .addComponent(OppField, 0, 99, Short.MAX_VALUE))))))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre1Label)
                    .addComponent(Nombre1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OppLabel)
                    .addComponent(OppField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre2Label)
                    .addComponent(Nombre2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CalculerBtn)
                .addGap(31, 31, 31)
                .addComponent(resultatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculerBtnActionPerformed
        String nomb1Str,nomb2Str,opp,resultatStr;
        double n1,n2,res=0;
        //
        nomb1Str=Nombre1Field.getText();
        nomb2Str=Nombre2Field.getText();
        opp=OppField.getSelectedItem().toString();
        
       //Convertion des chaines de caracteres ene entier
       n1=Integer.parseInt(nomb1Str);
       n2=Integer.parseInt(nomb2Str);
       if(!nomb1Str.contentEquals("")){
       if(opp.contentEquals("+")){
       res=n1+n2;
       }else if(opp.contentEquals("-")){ 
           res=n1-n2;
       }else if (opp.contentEquals("/")){
           if(n2!=0){
           res=n1/n2;
       }else{
               resultatStr="Error";
           }
           }else{
                   res=n1*n2;
       
       }
    
       resultatStr= res+"";
       
       ResultatField.setText(resultatStr);
       }else{
           JOptionPane.showMessageDialog(this, "Erreur");
       }
    }//GEN-LAST:event_CalculerBtnActionPerformed
    
    private void Nombre2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre2FieldActionPerformed

    private void ResultatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultatFieldActionPerformed

    private void Nombre1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre1FieldActionPerformed

    private void OppFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OppFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OppFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculerBtn;
    private javax.swing.JTextField Nombre1Field;
    private javax.swing.JLabel Nombre1Label;
    private javax.swing.JTextField Nombre2Field;
    private javax.swing.JLabel Nombre2Label;
    private javax.swing.JComboBox<String> OppField;
    private javax.swing.JLabel OppLabel;
    private javax.swing.JTextField ResultatField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel resultatPanel;
    // End of variables declaration//GEN-END:variables
}
