/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

/**
 *
 * @author ferdinand ATTIVI
 */
public class MaCalculatrice extends javax.swing.JFrame {

    /**
     * Creates new form MaCalculatrice
     */
    public MaCalculatrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        affichage = new javax.swing.JTextField();
        nbre7 = new javax.swing.JButton();
        nbre8 = new javax.swing.JButton();
        nbre9 = new javax.swing.JButton();
        nbre4 = new javax.swing.JButton();
        nbre5 = new javax.swing.JButton();
        nbre6 = new javax.swing.JButton();
        nbre1 = new javax.swing.JButton();
        nbre2 = new javax.swing.JButton();
        nbre3 = new javax.swing.JButton();
        nbre0 = new javax.swing.JButton();
        virg = new javax.swing.JButton();
        egal = new javax.swing.JButton();
        opp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PORPO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ravie", 2, 18))); // NOI18N

        affichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affichageActionPerformed(evt);
            }
        });

        nbre7.setText("7");
        nbre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre7ActionPerformed(evt);
            }
        });

        nbre8.setText("8");
        nbre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre8ActionPerformed(evt);
            }
        });

        nbre9.setText("9");
        nbre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre9ActionPerformed(evt);
            }
        });

        nbre4.setText("4");
        nbre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre4ActionPerformed(evt);
            }
        });

        nbre5.setText("5");
        nbre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre5ActionPerformed(evt);
            }
        });

        nbre6.setText("6");
        nbre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre6ActionPerformed(evt);
            }
        });

        nbre1.setText("1");
        nbre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre1ActionPerformed(evt);
            }
        });

        nbre2.setText("2");
        nbre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre2ActionPerformed(evt);
            }
        });

        nbre3.setText("3");
        nbre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre3ActionPerformed(evt);
            }
        });

        nbre0.setText("0");
        nbre0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbre0ActionPerformed(evt);
            }
        });

        virg.setText(".");
        virg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virgActionPerformed(evt);
            }
        });

        egal.setText("=");
        egal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egalActionPerformed(evt);
            }
        });

        opp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/", "ln", "e^" }));
        opp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(affichage, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nbre1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nbre7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(nbre4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nbre8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(nbre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nbre5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nbre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nbre9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(nbre3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nbre0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(virg)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(egal, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(affichage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nbre9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbre8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbre7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nbre4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(nbre5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nbre2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nbre1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nbre6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(nbre3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nbre0, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(virg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(opp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(egal, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addGap(126, 126, 126))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre4ActionPerformed
       String affiStr;
        int res = 4;
       
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre4ActionPerformed

    private void nbre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre5ActionPerformed
         String affiStr;
        int res;
        res=5;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre5ActionPerformed

    private void nbre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre6ActionPerformed
        String affiStr;
        int res;
        res=6;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre6ActionPerformed

    private void nbre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre2ActionPerformed
        String affiStr;
        int res;
        res=2;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre2ActionPerformed

    private void nbre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre3ActionPerformed
         String affiStr;
        int res;
        res=3;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre3ActionPerformed

    private void nbre0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre0ActionPerformed
         String affiStr;
        int res;
        res=0;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre0ActionPerformed

    private void virgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virgActionPerformed
           String affiStr;
        String res;
        res=".";
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_virgActionPerformed

    private void egalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egalActionPerformed
      String nbre9Str,nbre7Str,nbre8Str,nbre5Str,nbre4Str,nbre3Str,nbre2Str,nbre1Str,nbre0Str,OppStr,nbreStr,affiStr;
      int n4,n3,n2,n1,n0,n6 = 0,n5,n7,n8,n9 = 0;
      int res = 0;
      nbre7Str=nbre7.getText();
      nbre8Str=nbre8.getText();
      nbre5Str=nbre5.getText();
      nbre4Str=nbre4.getText();
      nbre3Str=nbre3.getText();
      nbre2Str=nbre2.getText();
      nbre1Str=nbre1.getText();
      nbre0Str=nbre0.getText();
      nbre9Str= nbre9.getText();
      OppStr=opp.getSelectedItem().toString();
      
       //
       n7=Integer.parseInt(nbre7Str);
       n8=Integer.parseInt(nbre8Str);
       n5=Integer.parseInt(nbre5Str);
       n4=Integer.parseInt(nbre4Str);
       n3=Integer.parseInt(nbre3Str);
       n2=Integer.parseInt(nbre2Str);
       n1=Integer.parseInt(nbre1Str);
       n0=Integer.parseInt(nbre0Str);
      int n[] = {n0,n1,n2,n3,n4,n5,n6,n7,n9};
       
       if(OppStr.contentEquals("+")){
      /* res= n + n;*/
       }else if(OppStr.contentEquals("-")){ 
           res=n7-n8;
       }else if (OppStr.contentEquals("/")){
           if(n7!=0){
           res=n7/n8;
       }else{
               affiStr="Error";
           }
           }else{
                   res=n7*n8;
       
       }
      affiStr=res+"";
      affichage.setText(affiStr);
       
       
    }//GEN-LAST:event_egalActionPerformed

    private void nbre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre7ActionPerformed
        String affiStr;
        int res;
        res=7;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
        
    }//GEN-LAST:event_nbre7ActionPerformed

    private void nbre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre8ActionPerformed
         String affiStr;
        int res;
        res=8;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre8ActionPerformed

    private void nbre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre9ActionPerformed
        String affiStr;
        int res;
        res=9;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre9ActionPerformed

    private void nbre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbre1ActionPerformed
         String affiStr;
        int res;
        res=1;
        
        affiStr=res+"";
        affichage.setText(affiStr);
       
    }//GEN-LAST:event_nbre1ActionPerformed

    private void oppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oppActionPerformed

    private void affichageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affichageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affichageActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaCalculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaCalculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaCalculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaCalculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaCalculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affichage;
    private javax.swing.JButton egal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nbre0;
    private javax.swing.JButton nbre1;
    private javax.swing.JButton nbre2;
    private javax.swing.JButton nbre3;
    private javax.swing.JButton nbre4;
    private javax.swing.JButton nbre5;
    private javax.swing.JButton nbre6;
    private javax.swing.JButton nbre7;
    private javax.swing.JButton nbre8;
    private javax.swing.JButton nbre9;
    private javax.swing.JComboBox<String> opp;
    private javax.swing.JButton virg;
    // End of variables declaration//GEN-END:variables
}
